on: 
  push:
    branches:
      - main

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v3
      with:
        source_repo: "https://github.com/AlonTzafari/glitch-server.git"
        source_branch: "main"
        destination_repo: ${{ secrets.GLITCH_GIT }}
        destination_branch: "master"
